routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Site\UdemaController@index')->name('udema');
Route::get('/blog/{category_id?}', 'Site\BlogController@index')->name('blog');
Route::get('/blog/{id}/post', 'Site\BlogController@show')->name('blog.show');
Route::post('/blog/{id}', 'Site\BlogController@comment')->name('blog.store')->middleware('auth');
Route::get('/course', 'Site\CourseController@index')->name('course');
Route::get('/course/{id}', 'Site\CourseController@show')->name('course.show');
Route::post('/course/{id}', 'Site\CourseController@course')->name('course.store')->middleware('auth');


Route::group(['prefix'=>'dashboard','middleware'=>'admin','as'=>'admin.','namespace'=>'\App\Http\Controllers\Admin'],function(){

    Route::get('/','AdminMainContoller@index')->name('main');
    Route::resource('users','UserController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('courses','CourseController');
    Route::resource('lessons','LessonController');
    Route::resource('reviews','ReviewController');
    Route::resource('comments','CommentController');
    Route::resource('requests','RequestController');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone','role','is_active','image',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function comments(){
        return $this->hasMany(Comment::class,'user_id');
    }

    public function setPasswordAttribute($val)
    {
        if (!empty($val)) {
            $this->attributes['password'] = bcrypt($val);
        }
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'user_courses', 'user_id', 'course_id')->withPivot('approval');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\User;
use App\Http\Requests\UserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $users = User::all();
        return view('Dashboard.Users.index' , [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('Dashboard.Users.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request,[
        'name'=>'required|max:191',
        'email'=>'required|email|max:191|unique:users,email',
        'phone'=>'required|max:191|unique:users,phone',
        'password'=>'required|min:6|confirmed',
        'role'=>'required|in:admin,user',
        'is_active'=>'required|boolean',
        'image'=>'sometimes|file|max:2048',
    ]);
        $inputs = $request->except(['image']);
        if($request->hasFile('image'))
        {
            $inputs['image']= uploadImg($request->image);
        }
        User::create($inputs);
        return redirect(route('admin.users.index'))
            ->with('success','User Added Succesfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::FindOrFail($id);
        $comments  = $user->comments;
        return view('Dashboard.Users.show',compact('user','comments'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('Dashboard.Users.Edit')
            ->with('user',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $this->validate($request,[
            'name'=>'required|max:191',
            'email'=>'required|email|max:191|unique:users,email,'.$id,
            'phone'=>'required|max:191|unique:users,phone,'.$id,
            'password'=>'nullable|min:6|confirmed',
            'role'=>'required|in:admin,user',
            'is_active'=>'required|boolean',
            'image'=>'nullable|file|max:2048',
        ]);

        $inputs = $request->except(['image']);
        if($request->hasFile('image'))
        {
            $inputs['image']= uploadImg($request->image);
        }

        $user->update($inputs);
        return redirect(route('admin.users.index'))
            ->with('success','User Updated Succesfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if(!$user) {
            return back()->with('error', 'User Not Found');
        }
        if(auth()->user()->id == $user->id) return back()->with('error','You Cannont Delet You MemberShip');
        $user->delete();
        return redirect(route('admin.users.index'))
            ->with('success','User Deleted Succesfully');
    }
}

resources/views/Dashboard/Users/add.blade.php
@extends('Dashboard.layout')

@section('title')
    Create New User
@endsection

@section('content')
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::open(['route' => 'admin.users.store', 'method' => 'post','files'=>true]) !!}
            @include('Dashboard.Users.form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/Dashboard/Users/edit.blade.php
@extends('Dashboard.layout')

@section('title')
    Edit {{$user->name}}
@endsection

@section('content')
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::model($user,['route' => ['admin.users.update' ,$user->id] ,'method' => 'put' , 'files' => true]) !!}
            @include('Dashboard.Users.form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/Dashboard/Users/form.blade.php
<div class="panel panel-flat">
    <div class="panel-heading">
@if(isset($user))
    <h6 class="panel-title">Edit {{$user->name}}</h6>
@else
    <h6 class="panel-title">Add New User</h6>
@endif
<div class="heading-elements">

</div>
</div>

    <div class="panel-body">
        <div class="form-group">
            <label>Your name: </label>
            {!! Form::text('name',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Your Email: </label>
            {!! Form::email('email',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Your Phone: </label>
            {!! Form::tel('phone',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Your password: </label>
            {!! Form::password('password',['class' => 'form-control']) !!}
        </div>


        <div class="form-group">
            <label>Repeat Your password: </label>
            {!! Form::password('password_confirmation',['class' => 'form-control']) !!}
        </div>

    <div class="form-group">
        <label>Select Status: </label>
        {!! Form::select('is_active', status(), null, ['placeholder' => 'Select User Role']) !!}
    </div>

    <div class="form-group">
        <label>Select Role: </label>
        {!! Form::select('role', roles(), null, ['placeholder' => 'Select User Role']) !!}
    </div>

    <div class="form-group col-md-12">
        <label class="text-semibold"> صورة العضو : </label>
        <div class="media no-margin-top">
            @if(isset($user))
                @if($user->image!=null)
                    <div class="media-left">
                        <a href="#"><img src="{{getimg($user->image)}}" style="width: 58px; height: 58px; border-radius: 2px;" alt=""></a>
                    </div>
                @endif
            @endif

            <div class="media-body">
                <input type="file" class="file-styled" name="image" data-height="200">
                <span class="help-block">الصيغ المسموح بها : gif, png, jpg , jpeg</span>
            </div>
        </div>
    </div>

    <div class="text-right">
        <button type="submit" class="btn bg-teal-400">Submit form <i class="icon-arrow-left13 position-right"></i></button>
    </div>
</div>
</div>

resources/views/Dashboard/Users/index.blade.php
@extends('Dashboard.layout')

@section('title')

Users

@endsection

@section('content')
    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">All Users Operations</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            You Can Show All Users And performs All operations like search , Edit , show And Delete
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
                <tr>
                    <th>#</th>
                    <th>name</th>
                    <th>email</th>
                    <th>phone</th>
                    <th>role</th>
                    <th>comments</th>
                    <th>Active</th>
                    <th>operations</th>


                </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)
                <tr>
                    <td>{{$user->id}}</td>
                    <td><a href="#">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone}}</td>

                    <td><span class="label label-success">{{$user->role}}</span></td>
                    <td><a href="{{route('admin.users.show' , ['id' => $user->id])}}">{{$user->comments->count()}}</a></td>
                    <td><span class="label label-success">{{status()[$user->is_active]}}</span></td>
                    <td>
                        <a href="{{route('admin.users.edit',['id'=>$user->id])}}" class="btn btn-default">
                            <i class="icon-pencil"></i>
                        </a>

                        <form action="{{route('admin.users.destroy',$user->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">
                                <i class="icon-trash"></i>
                            </button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

@endsection

resources/views/Dashboard/Users/show.blade.php
@extends('Dashboard.layout')

@section('title')
    Show {{$user->name}} Comments
@endsection

@section('content')
    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Show {{$user->name}} Comments</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            You Can Show All {{$user->name}} Comments And performs All operations like search , Edit , show And Delete
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th>#</th>
                <th>التعليق</th>

                <th>التاريخ</th>
            </tr>
            </thead>
            <tbody>
            @foreach($comments as $comment)
                <tr>
                    <td>{{$comment->id}}</td>
                    <td>{{$comment->comment}}</td>
                    <td>{{$comment->created_at}}</td>
                </tr>
            @endforeach



            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->





@endsection