routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Site\UdemaController@index')->name('udema');
Route::get('/blog/{category_id?}', 'Site\BlogController@index')->name('blog');
Route::get('/blog/{id}/post', 'Site\BlogController@show')->name('blog.show');
Route::post('/blog/{id}', 'Site\BlogController@comment')->name('blog.store')->middleware('auth');
Route::get('/course', 'Site\CourseController@index')->name('course');
Route::get('/course/{id}', 'Site\CourseController@show')->name('course.show');
Route::post('/course/{id}', 'Site\CourseController@course')->name('course.store')->middleware('auth');


Route::group(['prefix'=>'dashboard','middleware'=>'admin','as'=>'admin.','namespace'=>'\App\Http\Controllers\Admin'],function(){

    Route::get('/','AdminMainContoller@index')->name('main');
    Route::resource('users','UserController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('courses','CourseController');
    Route::resource('lessons','LessonController');
    Route::resource('reviews','ReviewController');
    Route::resource('comments','CommentController');
    Route::resource('requests','RequestController');
});

resources/views/Dashboard/navbar.blade.php
<!-- Main -->
<li class="navigation-header"><span>Control Panel</span> <i class="icon-menu" title="Main pages"></i></li>

{{--User Navbar--}}
<li class="active"><a href="{{route('admin.main')}}"><i class="icon-home4"></i> <span>Main</span></a></li>
<li>
    <a href="#"><i class="icon-users"></i> <span>Users Control</span></a>
    <ul>
        <li><a href="{{route('admin.users.index')}}">All Users</a></li>
        <li><a href="{{route('admin.users.create')}}">Create New User</a></li>
    </ul>
</li>

{{--Category Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Categories</span></a>
    <ul>
        <li><a href="{{route('admin.categories.index')}}">All Categories</a></li>
        <li><a href="{{route('admin.categories.create')}}">Create New Category</a></li>
    </ul>
</li>

{{--post Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Posts</span></a>
    <ul>
        <li><a href="{{route('admin.posts.index')}}">All Posts</a></li>
        <li><a href="{{route('admin.posts.create')}}">Create New Post</a></li>
    </ul>
</li>

{{--comment Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Comments</span></a>
    <ul>
        <li><a href="{{route('admin.comments.index')}}">All Comments</a></li>
        <li><a href="{{route('admin.comments.create')}}">Create New Comment</a></li>
    </ul>
</li>

{{--course Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Courses</span></a>
    <ul>
        <li><a href="{{route('admin.courses.index')}}">All Courses</a></li>
        <li><a href="{{route('admin.courses.create')}}">Create New Course</a></li>
    </ul>
</li>

{{--lesson Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Lessons</span></a>
    <ul>
        <li><a href="{{route('admin.lessons.index')}}">All Lessons</a></li>
        <li><a href="{{route('admin.lessons.create')}}">Create New Lesson</a></li>
    </ul>
</li>


{{--Review Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Reviews</span></a>
    <ul>
        <li><a href="{{route('admin.reviews.index')}}">All Reviews</a></li>
        <li><a href="{{route('admin.reviews.create')}}">Create New Review</a></li>
    </ul>
</li>

{{--Review Navbar--}}
<li>
    <a href="#"><i class="icon-cart"></i> <span>Requests</span></a>
    <ul>
        <li><a href="{{route('admin.requests.index')}}">All Request</a></li>
    </ul>
</li>

resources/views/Dashboard/scripts.blade.php
	<!-- Core JS files -->
	<script src="/admin/global_assets/js/plugins/loaders/pace.min.js"></script>
	<script src="/admin/global_assets/js/core/libraries/jquery.min.js"></script>
	<script src="/admin/global_assets/js/core/libraries/bootstrap.min.js"></script>
	<script src="/admin/global_assets/js/plugins/loaders/blockui.min.js"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script src="/admin/global_assets/js/plugins/visualization/d3/d3.min.js"></script>
	<script src="/admin/global_assets/js/plugins/visualization/d3/d3_tooltip.js"></script>
	<script src="/admin/global_assets/js/plugins/forms/styling/switchery.min.js"></script>
	<script src="/admin/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js"></script>
	<script src="/admin/global_assets/js/plugins/ui/moment/moment.min.js"></script>
	<script src="/admin/global_assets/js/plugins/pickers/daterangepicker.js"></script>

	<script src="/admin/assets/js/app.js"></script>
	<script src="/admin/global_assets/js/demo_pages/dashboard.js"></script>
	<!-- /theme JS files -->

resources/views/Dashboard/styles.blade.php
	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="/admin/global_assets/css/icons/icomoon/styles.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/core.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/components.min.css" rel="stylesheet" type="text/css">
	<link href="/admin/assets/css/colors.min.css" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->