routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Site\UdemaController@index')->name('udema');
Route::get('/blog/{category_id?}', 'Site\BlogController@index')->name('blog');
Route::get('/blog/{id}/post', 'Site\BlogController@show')->name('blog.show');
Route::post('/blog/{id}', 'Site\BlogController@comment')->name('blog.store')->middleware('auth');
Route::get('/course', 'Site\CourseController@index')->name('course');
Route::get('/course/{id}', 'Site\CourseController@show')->name('course.show');
Route::post('/course/{id}', 'Site\CourseController@course')->name('course.store')->middleware('auth');


Route::group(['prefix'=>'dashboard','middleware'=>'admin','as'=>'admin.','namespace'=>'\App\Http\Controllers\Admin'],function(){

    Route::get('/','AdminMainContoller@index')->name('main');
    Route::resource('users','UserController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('courses','CourseController');
    Route::resource('lessons','LessonController');
    Route::resource('reviews','ReviewController');
    Route::resource('comments','CommentController');
    Route::resource('requests','RequestController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title', 'description', 'image', 'category_id',
    ];

    public function category()
    {
        return $this->belongsTo(category::class,'category_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class,'post_id');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('Dashboard.Posts.index' ,[
            'posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Dashboard.Posts.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required|max:191|unique:posts,title',
            'description'=>'required|max:191',
            'image'=>'sometimes|file|max:2048',
            'category_id'=>'required'
        ]);

        $inputs = $request->except(['image']);
        if($request->hasFile('image'))
        {
            $inputs['image']= uploadImg($request->image);
        }
        Post::create($inputs);
        return redirect(route('admin.posts.index'))
            ->with('success','Post Added Succesfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('Dashboard.Posts.edit')
            ->with('post',$post);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);

        $this->validate($request,[
            'title'=>'required|max:191|unique:posts,title,'.$id,
            'description'=>'required|max:191',
            'image'=>'sometimes|file|max:2048',
            'category_id'=>'required'
        ]);

        $inputs = $request->except(['image']);
        if($request->hasFile('image'))
        {
            $inputs['image']= uploadImg($request->image);
        }

        $post->update($inputs);
        return redirect(route('admin.posts.index'))
            ->with('success','Post Updated Succesfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        if(!$post) return back()->with('error','Post Not Found');
        $post->delete();
        return redirect(route('admin.posts.index'))
            ->with('success','Post Deleted Succesfully');
    }
}

resources/views/Dashboard/Posts/add.blade.php
@extends('Dashboard.layout')

@section('title')
    Create New Post
@endsection

@section('content')
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::open(['route' => 'admin.posts.store', 'method' => 'post','files'=>true]) !!}
        @include('Dashboard.Posts.form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/Dashboard/Posts/edit.blade.php
@extends('Dashboard.layout')

@section('title')
    Edit {{$post->title}}
@endsection

@section('content')
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::model($post,['route' => ['admin.posts.update' ,$post->id] ,'method' => 'put' , 'files' => true]) !!}
        @include('Dashboard.Posts.form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/Dashboard/Posts/form.blade.php
<div class="panel panel-flat">
    <div class="panel-heading">
        @if(isset($post))
            <h6 class="panel-title">Edit {{$post->title}}</h6>
        @else
            <h6 class="panel-title">Add New Post</h6>
        @endif
        <div class="heading-elements">

        </div>
    </div>

    <div class="panel-body">
        <div class="form-group">
            <label>Post title: </label>
            {!! Form::text('title',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Post description: </label>
            {!! Form::text('description',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Categories: </label>
            {!! Form::select('category_id', categories(), null, ['placeholder' => 'Select User Status']) !!}
        </div>


        <div class="form-group col-md-12">
            <label class="text-semibold"> Post Image : </label>
            <div class="media no-margin-top">
                @if(isset($post))
                    @if($post->image!=null)
                        <div class="media-left">
                            <a href="#"><img src="{{getimg($post->image)}}" style="width: 58px; height: 58px; border-radius: 2px;" alt=""></a>
                        </div>
                    @endif
                @endif

                <div class="media-body">
                    <input type="file" class="file-styled" name="image" data-height="200">
                    <span class="help-block">الصيغ المسموح بها : gif, png, jpg , jpeg</span>
                </div>
            </div>
        </div>

        <div class="text-right">
            <button type="submit" class="btn bg-teal-400">Submit form <i class="icon-arrow-left13 position-right"></i></button>
        </div>
    </div>
</div>

resources/views/Dashboard/Posts/index.blade.php
@extends('Dashboard.layout')

@section('title')

    Posts

@endsection

@section('content')
    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">All Posts Operations</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            You Can Show All Posts And performs All operations like search , Edit , show And Delete
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th>#</th>
                <th>title</th>
                <th>image</th>
                <th>description</th>
                <th>Category</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($posts as $post)
                <tr>
                    <td>{{$post->id}}</td>
                    <td>{{$post->title}}</td>
                    <td>
                        <div class="media no-margin-top">
                            @if(isset($post))
                                @if($post->image!=null)
                                    <div class="media-left">
                                        <a href="#"><img src="{{getimg($post->image)}}"
                                                         style="width: 58px; height: 58px; border-radius: 2px;" alt=""></a>
                                    </div>
                                @endif
                            @endif
                        </div>
                    </td>
                    <td>{{$post->description}}</td>
                    <td>{{$post->category->name}}</td>
                    <td>
                        <a href="{{route('admin.posts.edit',['id'=>$post->id])}}" class="btn btn-default">
                            <i class="icon-pencil"></i>
                        </a>

                        <form action="{{route('admin.posts.destroy',$post->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">
                                <i class="icon-trash"></i>
                            </button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

@endsection