routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'Site\UdemaController@index')->name('udema');
Route::get('/blog/{category_id?}', 'Site\BlogController@index')->name('blog');
Route::get('/blog/{id}/post', 'Site\BlogController@show')->name('blog.show');
Route::post('/blog/{id}', 'Site\BlogController@comment')->name('blog.store')->middleware('auth');
Route::get('/course', 'Site\CourseController@index')->name('course');
Route::get('/course/{id}', 'Site\CourseController@show')->name('course.show');
Route::post('/course/{id}', 'Site\CourseController@course')->name('course.store')->middleware('auth');


Route::group(['prefix'=>'dashboard','middleware'=>'admin','as'=>'admin.','namespace'=>'\App\Http\Controllers\Admin'],function(){

    Route::get('/','AdminMainContoller@index')->name('main');
    Route::resource('users','UserController');
    Route::resource('categories','CategoryController');
    Route::resource('posts','PostController');
    Route::resource('courses','CourseController');
    Route::resource('lessons','LessonController');
    Route::resource('reviews','ReviewController');
    Route::resource('comments','CommentController');
    Route::resource('requests','RequestController');
});

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    protected $fillable = [
    'title', 'description', 'link', 'course_id', 'duration',
    ];

    public function course()
    {
        return $this->belongsTo(Course::class,'course_id');
    }
}

app/Http/Controllers/Admin/LessonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Lesson;
use Illuminate\Http\Request;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessons = Lesson::all();
        return view('Dashboard.Lessons.index' , [
            'lessons' => $lessons
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Dashboard.Lessons.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Lesson::create($this->validate($request,[
            'title'=>'required|max:191',
            'description'=>'required',
            'link'=>'required|max:191',
            'course_id'=>'required',
            'duration'=>'required|numeric|gt:0'
        ]));
        return redirect(route('admin.lessons.index'))
            ->with('success','Lesson Added Succesfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lesson = Lesson::findOrFail($id);
        return view('Dashboard.Lessons.edit')
            ->with('lesson',$lesson);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $lesson =Lesson::find($id);

        $lesson->update($this->validate($request,[
            'title'=>'required|max:191',
            'description'=>'required',
            'link'=>'required|max:191',
            'course_id'=>'required',
            'duration'=>'required|numeric|gt:0'
        ]));
        return redirect(route('admin.lessons.index'))
            ->with('success','Lesson Updated Succesfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lesson = Lesson::find($id);
        if(!$lesson) return back()->with('error','Lesson Not Found');
        $lesson->delete();
        return redirect(route('admin.lessons.index'))
            ->with('success','Lesson Deleted Succesfully');
    }
}

resources/views/Dashboard/Lessons/add.blade.php
@extends('Dashboard.layout')

@section('title')
    Create New Lesson
@endsection

@section('content')
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::open(['route' => 'admin.lessons.store', 'method' => 'post','files'=>true]) !!}
        @include('Dashboard.Lessons.form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/Dashboard/Lessons/edit.blade.php
@extends('Dashboard.layout')

@section('title')
    Edit {{$lesson->title}}
@endsection

@section('content')
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        {!! Form::model($lesson,['route' => ['admin.lessons.update' ,$lesson->id] ,'method' => 'put' , 'files' => true]) !!}
        @include('Dashboard.Lessons.form')
        {!! Form::close() !!}
    </div>
@endsection

resources/views/Dashboard/Lessons/form.blade.php
<div class="panel panel-flat">
    <div class="panel-heading">
        @if(isset($lesson))
            <h6 class="panel-title">Edit {{$lesson->title}}</h6>
        @else
            <h6 class="panel-title">Add New Lesson</h6>
        @endif
        <div class="heading-elements">

        </div>
    </div>

    <div class="panel-body">
        <div class="form-group">
            <label>Lesson title: </label>
            {!! Form::text('title',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Lesson description: </label>
            {!! Form::textarea('description',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Lesson link: </label>
            {!! Form::text('link',null,['class' => 'form-control']) !!}
        </div>

        <div class="form-group">
            <label>Course Categories: </label>
            {!! Form::select('course_id', courses(), null, ['class' => 'form-control','placeholder' => 'Select Course title']) !!}
        </div>

        <div class="form-group">
            <label>Lesson duration: </label>
            {!! Form::number('duration',null,['class' => 'form-control']) !!}

        </div>

        <div class="text-right">
            <button type="submit" class="btn bg-teal-400">Submit form <i class="icon-arrow-left13 position-right"></i></button>
        </div>
    </div>
</div>

resources/views/Dashboard/Lessons/index.blade.php
@extends('Dashboard.layout')

@section('title')

    Lessons

@endsection

@section('content')
    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">All Lessons Operations</h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="collapse"></a></li>
                    <li><a data-action="reload"></a></li>
                    <li><a data-action="close"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            You Can Show All Lessons And performs All operations like search , Edit , show And Delete
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th>#</th>
                <th>title</th>
                <th>description</th>
                <th>link</th>
                <th>Course name</th>
                <th>duration</th>
                <th>Operation</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($lessons as $lesson)
                <tr>
                    <td>{{$lesson->id}}</td>
                    <td>{{$lesson->title}}</td>
                    <td>{{$lesson->description}}</td>
                    <td><a href="{{$lesson->link}}">Watch now</a></td>
                    <td><span class="label label-success">{{$lesson->course->title}}</span></td>
                    <td>{{$lesson->duration}}</td>
                    <td>
                        <a href="{{route('admin.lessons.edit',['id'=>$lesson->id])}}" class="btn btn-default">
                            <i class="icon-pencil"></i>
                        </a>

                        <form action="{{route('admin.lessons.destroy',$lesson->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger">
                                <i class="icon-trash"></i>
                            </button>
                        </form>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

@endsection